### PR TITLE
fix: using custom docker daemon (e.g podman)

### PR DESCRIPTION
**Pull request by matejvasek**
The `func` binary is now aware of DOCKER_HOST environment variable.

Signed-off-by: Matej Vasek <mvasek@redhat.com>

### CODE REVIEW

**Comment by matejvasek** [comment]
@dsimansk please check if the changed dependencies don't affect integration with `kn`.

**Comment by matejvasek** [comment]
resolves #188

**Review by zroubalik — APPROVED** [review]
Looking good, though I am not sure if this fully solves #188, because for pushing the image, docker binary is still being used.

**Comment by matejvasek** [comment]
@zroubalik good catch, we should call docker API client there, not binary.

**Comment by matejvasek** [comment]
@zroubalik now I recall it's not that easy isn't it?

**Comment by lance** [comment]
> now I recall it's not that easy is it?

Looking at the [docs](https://pkg.go.dev/github.com/docker/docker/client#Client.ImagePush) and a [blog post](https://www.loginradius.com/blog/async/build-push-docker-images-golang/), it seems easy enough. We would just need to handle username and password directly in our CLI instead of relying on the client to be logged in.

**Comment by matejvasek** [comment]
>  We would just need to handle username and password directly in our CLI instead of relying on the client to be logged in.

This make sense. Especially if the user uses both `docker` and `podman`, since the user might be logged in only in one of them (or even might be logged under different usernames in `podman` and `docker`).

**Comment by dsimansk** [comment]
> @dsimansk please check if the changed dependencies don't affect integration with `kn`.

@matejvasek sorry I missed that. Well I'm pretty sure something will brake, because next kn 0.20 is not on k8s `19.x` yet.

**Pull request merged**
