### PR TITLE
src: rename bosonFunc fn

### PR DESCRIPTION
**Pull request by lkingland**
When we renamed `faas` to `func`, we lost the ability to simply import the package, as the name now conflicts with the builtin `func`.  The solution at the time was the somewhat verbose, though correct, `bosonFunc`.  At some point, I believe @lance used simply `fn` in a test somewhere.  I much prefer this shorter incarnation, and this PR proposes adopting `fn` as the import name throughout.

### CODE REVIEW

**Review by matejvasek — APPROVED** [review]

**Comment by matejvasek** [comment]
This is only refactor with no effect on functionality, righ? @lkingland

**Review by lance — APPROVED** [review]
Touches a lot of files, but all just name changes. LGTM

**Comment by lance** [comment]
> This is only refactor with no effect on functionality, righ? @lkingland

Yes - we discussed this in the call today. Just renaming.

**Comment by lkingland** [comment]
> This is only refactor with no effect on functionality, righ? @lkingland 

That is correct.

**Comment by lance** [comment]
I was worried this would happen with so many files touched. @lkingland can you resolve the conflicts?

**Comment by lkingland** [comment]
Absolutely, no problem. I expected to take care of the merge once approved.

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
