### PR TITLE
fix: change --format flag to --output for list and describe commands

### PR DESCRIPTION
**Pull request by lance**
Fixes: https://github.com/boson-project/func/issues/223

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Review by zroubalik — CHANGES_REQUESTED** [review]
This should be changed as well: https://github.com/boson-project/func/blob/main/docs/commands.md#describe

**Comment by lance** [comment]
> This should be changed as well: https://github.com/boson-project/func/blob/main/docs/commands.md#describe

@zroubalik done - ptal

**Comment by matejvasek** [comment]
Why did go.mod and files in template change?

**Comment by lance** [comment]
> Why did go.mod and files in template change?

Hmm - strange. I will revert those. I think there might be some problem when testing where `package.json` is updated with a point release dependency, which changes `package-lock.json`, and ultimately `pkged.go`.

**Comment by lance** [comment]
@matejvasek fixed

**Comment by lance** [comment]
@matejvasek yeah - `npm install` was updating package-lock.json. See https://github.com/boson-project/func/pull/251

**Review by zroubalik — APPROVED** [review]

**Pull request merged**
